/**
 * core/hookInstaller.ts — Install / uninstall the pre-push hook (v2.4.0)
 *
 * The hook is a tiny POSIX shell script that calls
 *   `node "<extension-install-path>/scripts/check-pipelines.js" --mode=<mode>`
 * with the list of pipeline files about to be pushed (computed from
 * `git diff --name-only @{push}..HEAD` plus existing files at the
 * known pipeline paths).
 *
 * Design notes (see v2.4 plan):
 *  - Hook respects existing hooks: if `.git/hooks/pre-push` already exists
 *    and was NOT written by us (no marker), we refuse to overwrite and
 *    surface options ("Replace / Append / Cancel"). Marker on our hook is
 *    the literal string `# evolve-ai-pipeline-check` on a comment line.
 *  - Husky detection: if `.husky/` exists, we offer to write to
 *    `.husky/pre-push` instead (different append semantics; Husky appends
 *    its own management). Otherwise our hook gets overwritten next time
 *    `husky install` runs.
 *  - Cross-platform: POSIX shell. Works on Git for Windows (MINGW64 sh),
 *    macOS, and Linux. We never write a .bat / .ps1 hook.
 */

import * as fs   from 'fs';
import * as path from 'path';

export const HOOK_MARKER = '# evolve-ai-pipeline-check';
const HOOK_FILENAME = 'pre-push';

export type HookState =
  | { kind: 'none' }                                      // no hook installed
  | { kind: 'ours';   path: string }                      // our hook is installed
  | { kind: 'theirs'; path: string }                      // some other hook exists
  | { kind: 'husky';  huskyPath: string };                // Husky is managing hooks

export interface InstallOptions {
  /** Repository root (where `.git/` lives). */
  repoRoot:        string;
  /** Absolute path to scripts/check-pipelines.js (resolved by caller). */
  scriptPath:      string;
  /** Mode passed to the script: 'block' | 'warn' | 'off'. */
  mode:            'block' | 'warn' | 'off';
  /** When state is 'theirs': 'replace' | 'append'. Ignored otherwise. */
  conflictAction?: 'replace' | 'append';
}

export interface InstallResult {
  ok:      boolean;
  message: string;
  /** Path to the hook file we wrote, on success. */
  path?:   string;
}

// ── Detection ────────────────────────────────────────────────────────────────

/** Detect what hook state the repo is in. Never throws. */
export function detectHookState(repoRoot: string): HookState {
  const huskyDir = path.join(repoRoot, '.husky');
  if (fs.existsSync(huskyDir)) {
    const huskyHook = path.join(huskyDir, HOOK_FILENAME);
    return { kind: 'husky', huskyPath: huskyHook };
  }
  const hookPath = _resolveHooksDir(repoRoot)
    .map(d => path.join(d, HOOK_FILENAME))
    .find(p => fs.existsSync(p));
  if (!hookPath) return { kind: 'none' };
  try {
    const content = fs.readFileSync(hookPath, 'utf8');
    if (content.includes(HOOK_MARKER)) return { kind: 'ours',   path: hookPath };
    return { kind: 'theirs', path: hookPath };
  } catch {
    return { kind: 'theirs', path: hookPath };  // safer to assume not ours
  }
}

/**
 * Read the core.hooksPath override (if set) and return candidate hook
 * directories in priority order. Most repos use `.git/hooks`; teams using
 * shared hook collections often set `core.hooksPath = .githooks`.
 */
function _resolveHooksDir(repoRoot: string): string[] {
  const candidates: string[] = [];
  const cfg = path.join(repoRoot, '.git', 'config');
  if (fs.existsSync(cfg)) {
    try {
      const text = fs.readFileSync(cfg, 'utf8');
      const m = /^\s*hooksPath\s*=\s*(.+)$/m.exec(text);
      if (m) {
        const override = m[1].trim();
        const abs = path.isAbsolute(override) ? override : path.join(repoRoot, override);
        candidates.push(abs);
      }
    } catch { /* ignore */ }
  }
  candidates.push(path.join(repoRoot, '.git', 'hooks'));
  return candidates;
}

// ── Hook script template ─────────────────────────────────────────────────────

function _buildHookScript(scriptPath: string, mode: 'block' | 'warn' | 'off'): string {
  // POSIX shell. The script reads `<local_ref> <local_sha> <remote_ref> <remote_sha>`
  // lines from stdin (pre-push hook contract); we compute the file diff with
  // `git diff --name-only` between local and remote HEAD.
  //
  // If `node` is not on PATH we exit 0 (don't block) and print a one-line note —
  // a missing node should not break a developer's push.
  //
  // Path uses forward slashes so MINGW64 sh on Windows can resolve it.
  const norm = scriptPath.replace(/\\/g, '/');
  return [
    '#!/bin/sh',
    HOOK_MARKER,
    `# Generated by Evolve AI v2.4.0. Re-run "Evolve AI: Install CI/CD Pre-Push Hook"`,
    '# to update. Bypass once: git push --no-verify',
    '',
    'set -u',
    '',
    'if ! command -v node >/dev/null 2>&1; then',
    '  echo "evolve-ai hook: node not on PATH, skipping pipeline check" >&2',
    '  exit 0',
    'fi',
    '',
    `SCRIPT="${norm}"`,
    'if [ ! -f "$SCRIPT" ]; then',
    '  echo "evolve-ai hook: $SCRIPT not found (extension uninstalled?)." >&2',
    '  echo "  remove with: rm \\".git/hooks/pre-push\\"  or reinstall the extension." >&2',
    '  exit 0',
    'fi',
    '',
    '# Read remote update lines from stdin (pre-push hook contract).',
    '# Build the union of changed files across all refs being pushed.',
    'FILES=""',
    'while read local_ref local_sha remote_ref remote_sha; do',
    '  [ "$local_sha" = "0000000000000000000000000000000000000000" ] && continue',
    '  if [ "$remote_sha" = "0000000000000000000000000000000000000000" ]; then',
    '    # Branch is new on the remote — diff against the merge-base with origin/HEAD.',
    '    BASE=$(git merge-base "$local_sha" origin/HEAD 2>/dev/null || true)',
    '    [ -z "$BASE" ] && BASE=$(git rev-list --max-parents=0 "$local_sha" | tail -n 1)',
    '    NEW=$(git diff --name-only "$BASE" "$local_sha" 2>/dev/null || true)',
    '  else',
    '    NEW=$(git diff --name-only "$remote_sha" "$local_sha" 2>/dev/null || true)',
    '  fi',
    '  FILES=$(printf "%s\\n%s" "$FILES" "$NEW")',
    'done',
    '',
    'FILES=$(printf "%s" "$FILES" | sed "/^$/d" | sort -u)',
    '',
    `# Pass files via NUL-separated stdin to node, with --mode=${mode}.`,
    `printf "%s" "$FILES" | tr "\\n" "\\0" | node "$SCRIPT" --mode=${mode}`,
    'exit $?',
    '',
  ].join('\n');
}

// ── Install / uninstall ──────────────────────────────────────────────────────

export function installHook(opts: InstallOptions): InstallResult {
  const { repoRoot, scriptPath, mode, conflictAction } = opts;
  const gitDir = path.join(repoRoot, '.git');
  if (!fs.existsSync(gitDir)) {
    return { ok: false, message: 'Not a git repository (no .git directory). Run `git init` first.' };
  }

  const state = detectHookState(repoRoot);

  // Husky path — write to .husky/pre-push instead.
  if (state.kind === 'husky') {
    return _installHuskyHook(state.huskyPath, scriptPath, mode);
  }

  // Resolve hooks dir (respects core.hooksPath if set).
  const hooksDirs = _resolveHooksDir(repoRoot);
  const hooksDir  = hooksDirs[0];   // use the highest-priority one
  try {
    fs.mkdirSync(hooksDir, { recursive: true });
  } catch (e) {
    return { ok: false, message: `Could not create hooks dir ${hooksDir}: ${(e as Error).message}` };
  }
  const targetPath = path.join(hooksDir, HOOK_FILENAME);

  // Conflict: existing non-evolve hook.
  if (state.kind === 'theirs') {
    if (!conflictAction) {
      return {
        ok:      false,
        message: `An existing pre-push hook is present at ${state.path}. Re-run install with conflictAction set to 'replace' or 'append'.`,
      };
    }
    if (conflictAction === 'append') {
      // Append a call to our checker to the existing hook. We deliberately
      // append rather than replace so the user's hook keeps running.
      const append = [
        '',
        HOOK_MARKER + ' (appended by Evolve AI)',
        `# Bypass: git push --no-verify`,
        `node "${scriptPath.replace(/\\/g, '/')}" --mode=${mode} || exit $?`,
        '',
      ].join('\n');
      try {
        fs.appendFileSync(state.path, append);
        return { ok: true, message: `Appended pre-push check to existing hook at ${state.path}.`, path: state.path };
      } catch (e) {
        return { ok: false, message: `Could not append to ${state.path}: ${(e as Error).message}` };
      }
    }
    // conflictAction === 'replace' — fall through to overwrite.
  }

  const script = _buildHookScript(scriptPath, mode);
  try {
    fs.writeFileSync(targetPath, script, { mode: 0o755 });
    // On Windows, fs.writeFileSync ignores mode — make it executable best-effort.
    try { fs.chmodSync(targetPath, 0o755); } catch { /* ignore on FS that doesn't support */ }
  } catch (e) {
    return { ok: false, message: `Could not write hook at ${targetPath}: ${(e as Error).message}` };
  }
  return { ok: true, message: `Installed pre-push hook at ${targetPath} (mode=${mode}).`, path: targetPath };
}

function _installHuskyHook(huskyHookPath: string, scriptPath: string, mode: string): InstallResult {
  // Husky 8+ hook format: a shell script that sources `_/husky.sh` then runs commands.
  // We APPEND our line to whatever's there (rather than overwrite), so Husky-managed
  // hooks keep functioning. If it already contains our marker, we replace just our line.
  const ourLine = `node "${scriptPath.replace(/\\/g, '/')}" --mode=${mode}  ${HOOK_MARKER}`;
  let existing = '';
  try { existing = fs.readFileSync(huskyHookPath, 'utf8'); } catch { /* file doesn't exist yet */ }

  let updated: string;
  if (existing.includes(HOOK_MARKER)) {
    // Replace the existing marker line in place so settings updates apply.
    updated = existing.split('\n').map(line => line.includes(HOOK_MARKER) ? ourLine : line).join('\n');
  } else if (existing.length > 0) {
    updated = existing.trimEnd() + '\n' + ourLine + '\n';
  } else {
    updated = [
      '#!/usr/bin/env sh',
      '. "$(dirname -- "$0")/_/husky.sh"',
      '',
      ourLine,
      '',
    ].join('\n');
  }

  try {
    fs.mkdirSync(path.dirname(huskyHookPath), { recursive: true });
    fs.writeFileSync(huskyHookPath, updated, { mode: 0o755 });
    try { fs.chmodSync(huskyHookPath, 0o755); } catch { /* ignore */ }
  } catch (e) {
    return { ok: false, message: `Could not write Husky hook at ${huskyHookPath}: ${(e as Error).message}` };
  }
  return { ok: true, message: `Installed pre-push check into Husky hook at ${huskyHookPath} (mode=${mode}).`, path: huskyHookPath };
}

/**
 * Remove our hook. If the file is ENTIRELY ours, we delete it.
 * If the file contains our marker but also other content (we'd appended), we
 * strip just our lines.
 * If the file is not ours, we refuse and report — never delete other people's hooks.
 */
export function uninstallHook(repoRoot: string): InstallResult {
  const state = detectHookState(repoRoot);

  if (state.kind === 'none') {
    return { ok: true, message: 'No pre-push hook to remove.' };
  }

  if (state.kind === 'husky') {
    return _uninstallHuskyHook(state.huskyPath);
  }

  // 'ours' or 'theirs'.
  let content = '';
  try { content = fs.readFileSync(state.path, 'utf8'); } catch { /* file gone */ return { ok: true, message: 'Hook file already gone.' }; }

  if (!content.includes(HOOK_MARKER)) {
    return { ok: false, message: `Hook at ${state.path} was not installed by Evolve AI. Refusing to remove.` };
  }

  // Strip our marker block. If only our content remains, delete the file.
  // Heuristic: if the file starts with our shebang + marker (full ownership), delete.
  const lines = content.split('\n');
  if (lines.length > 1 && lines[0].startsWith('#!') && lines[1] === HOOK_MARKER) {
    try { fs.unlinkSync(state.path); }
    catch (e) { return { ok: false, message: `Could not delete ${state.path}: ${(e as Error).message}` }; }
    return { ok: true, message: `Removed pre-push hook at ${state.path}.` };
  }

  // Otherwise: strip the appended block we added.
  const stripped = content.split('\n').filter((line, i, arr) => {
    if (line.includes(HOOK_MARKER)) return false;
    // Strip the `node ".../check-pipelines.js"…` line we appended just below the marker.
    const prev = arr[i - 1] || '';
    if (prev.includes(HOOK_MARKER) && /check-pipelines\.js/.test(line)) return false;
    return true;
  }).join('\n');

  try {
    fs.writeFileSync(state.path, stripped);
    return { ok: true, message: `Removed Evolve AI's pre-push check from ${state.path}. Other hook content preserved.` };
  } catch (e) {
    return { ok: false, message: `Could not rewrite ${state.path}: ${(e as Error).message}` };
  }
}

function _uninstallHuskyHook(huskyHookPath: string): InstallResult {
  let content = '';
  try { content = fs.readFileSync(huskyHookPath, 'utf8'); }
  catch { return { ok: true, message: 'Husky pre-push hook already absent.' }; }

  if (!content.includes(HOOK_MARKER)) {
    return { ok: false, message: `Husky hook at ${huskyHookPath} was not modified by Evolve AI. Refusing to alter.` };
  }

  const stripped = content.split('\n').filter(l => !l.includes(HOOK_MARKER)).join('\n');
  try {
    fs.writeFileSync(huskyHookPath, stripped);
    return { ok: true, message: `Removed pre-push check from Husky hook at ${huskyHookPath}.` };
  } catch (e) {
    return { ok: false, message: `Could not rewrite ${huskyHookPath}: ${(e as Error).message}` };
  }
}
