/**
 * fde/runbookGenerator.ts — Client Handoff Runbook & Architecture Generator
 *
 * For Forward Deployed Engineers (FDEs) to generate complete, client-ready handoff
 * documentation at the conclusion of a pilot or engagement.
 *
 * Outputs:
 *  - ARCHITECTURE.md (with interactive Mermaid diagrams)
 *  - DEPLOYMENT_RUNBOOK.md (Client IT operations guide)
 *  - DATA_DICTIONARY.md (Column-by-column transformation mapping)
 *  - ENVIRONMENT_CATALOG.md (Environment variable reference)
 */

import { FdeEngagementState } from './fdeContext';

export class RunbookGenerator {
  static generateArchitectureDoc(state: FdeEngagementState): string {
    const client = state.clientName || 'Client';
    const targetVpc = state.targetVpc || 'gcp-firebase';

    let schemaFlows = '';
    const marts = state.dataMarts || [];

    if (state.schemaMappings.length > 0 || marts.length > 0) {
      const stagingFlows = state.schemaMappings.map((m) => {
        const cleanSrc = m.sourceName.replace(/[^a-zA-Z0-9_]/g, '_');
        const cleanTgt = m.targetModelName.replace(/[^a-zA-Z0-9_]/g, '_');
        return `        ${cleanSrc}["Raw Source: ${m.sourceName}\\n(${m.columns.length} columns)"] --> ${cleanTgt}["dbt Staging: ${m.targetModelName}\\n(Type Casts & Renaming)"]`;
      }).join('\n');

      let martFlows = '';
      if (marts.length > 0) {
        martFlows = marts.map((mart) => {
          const cleanMart = mart.martName.replace(/[^a-zA-Z0-9_]/g, '_');
          const baseCte = mart.baseModel.replace(/[^a-zA-Z0-9_]/g, '_');
          const joinCtes = (mart.joins || []).map(j => (j.joinModel || '').replace(/[^a-zA-Z0-9_]/g, '_')).filter(Boolean);
          const joinLines = joinCtes.map(j => `        ${j} --> ${cleanMart}`).join('\n');
          return `        ${baseCte} --> ${cleanMart}["dbt Mart: ${mart.martName}\\n(${mart.dimensions.length} dims • ${mart.metrics.length} metrics)"]\n${joinLines}\n        ${cleanMart} --> Database`;
        }).join('\n');
      } else {
        martFlows = state.schemaMappings.map(m => `        ${m.targetModelName.replace(/[^a-zA-Z0-9_]/g, '_')} --> Database`).join('\n');
      }

      schemaFlows = `${stagingFlows}\n${martFlows}`;
    } else {
      schemaFlows = `        RawData["Raw Client Data\\n(CSV / Oracle / SQL)"] --> StagingModel["dbt Staging Model\\n(Type Casts & Renaming)"]\n        StagingModel --> Database`;
    }

    let apiFlows = '';
    if (state.apiConnectors.length > 0) {
      apiFlows = state.apiConnectors.map((c) => {
        const cleanConn = c.connectorName.replace(/[^a-zA-Z0-9_]/g, '_');
        return `        ${cleanConn}_Api["External API: ${c.connectorName}\\n(${c.baseUrl})"] --> ${cleanConn}_Sdk["Resilient SDK: ${c.connectorName}\\n(Auth: ${c.authType})"]\n        ${cleanConn}_Sdk --> Backend`;
      }).join('\n');
    } else {
      apiFlows = `        ClientApi["Client Internal APIs\\n(REST / Webhooks)"] --> ResilientSdk["Resilient Connector SDK\\n(Retries & Rate Limits)"]\n        ResilientSdk --> Backend`;
    }

    const cloudProvider = (state.deployment?.discoveredCloudResources?.provider || targetVpc || 'gcp').toUpperCase();
    const vpcInfo = state.deployment?.vpcId ? `\\n(VPC: ${state.deployment.vpcId})` : '';

    return `# ${client} — System Architecture & Integration Blueprint

> **Generated by Evolve AI (Forward Deployed Engineer Suite)**  
> **Engagement Target:** ${client} Production & Pilot Deployment  
> **Infrastructure Target:** ${cloudProvider} ${vpcInfo}  

---

## 1. Executive System Overview & Data Lineage

This document specifies the end-to-end architecture, data lineage flows, and deployment topology implemented for the **${client}** pilot engagement.

\`\`\`mermaid
graph TD
    subgraph Client Data Ingestion & Mart Layer
${schemaFlows}
    end

    subgraph External & Connected API Feeds
${apiFlows}
    end

    subgraph Cloud Delivery Layer (${cloudProvider})
        Frontend["Web & App Frontends\\n(SPA + Edge Caching)"]
        Backend["Compute Services / Containers\\n(${state.deployment?.cpu || '1'} vCPU · ${state.deployment?.memory || '1Gi'})"]
        Database["PostgreSQL / Supabase / Lakehouse\\n(Relational & Analytics)"]
    end

    Frontend --> Backend
    Backend --> Database
\`\`\`

---

## 2. Ingested Data Models & Transformations

### Staging Models (Phase 1A)
| Source Dataset | Target Model | Dialect | Columns | Status |
| :--- | :--- | :--- | :---: | :--- |
${state.schemaMappings.map(m => `| \`${m.sourceName}\` | \`${m.targetModelName}\` | \`${m.dialect}\` | ${m.columns.length} columns | Active |`).join('\n') || '| *(No schema models mapped yet)* | - | - | - | - |'}

### Downstream Business Marts (Phase 1B)
| Mart Name | Base Model | Joins | Dimensions | Metrics | Status |
| :--- | :--- | :--- | :---: | :---: | :--- |
${marts.map(mart => `| \`${mart.martName}\` | \`${mart.baseModel}\` | ${(mart.joins || []).map(j => `${j.joinType} ${j.joinModel}`).join(', ') || 'None'} | ${mart.dimensions.length} | ${mart.metrics.length} | Active |`).join('\n') || '| *(No data marts generated yet)* | - | - | - | - | - |'}

---

## 3. Connected APIs & External Feeds

| Connector Name | Base URL | Auth Strategy | Endpoints | Status |
| :--- | :--- | :--- | :---: | :--- |
${state.apiConnectors.map(c => `| \`${c.connectorName}\` | \`${c.baseUrl}\` | \`${c.authType}\` | ${c.endpoints.length} endpoints | Active |`).join('\n') || '| *(No API connectors registered)* | - | - | - | - |'}

---

## 4. Multi-Cloud Infrastructure & Security Posture

* **Compute Target:** ${cloudProvider} (${state.deployment?.cpu || '1'} vCPU, ${state.deployment?.memory || '1Gi'} Memory, GPU: ${state.deployment?.gpu || 'None'})
* **Network Isolation:** Ingress set to \`${state.deployment?.ingress || 'internal'}\` within VPC \`${state.deployment?.vpcId || 'default'}\`.
* **Secrets Provider:** \`${state.deployment?.secretsProvider || 'Cloud Secret Manager'}\`.
* **Air-Gapped Ready:** The deployment is compatible with strict air-gapped and non-exfiltrating client boundaries.
`;
  }

  static generateDeploymentRunbook(state: FdeEngagementState): string {
    const client = state.clientName || 'Client';

    return `# ${client} — Operations & Deployment Runbook

> **Audience:** Client IT, DevOps, and Platform Engineering Teams  
> **Maintained by:** Forward Deployed Engineering (FDE)  

---

## 1. Quick-Start Deployment

To deploy updates to the client environment, execute the cross-platform deployment script from the project root:

\`\`\`bash
# Linux / macOS (Bash)
./scripts/deploy.sh pilot all

# Windows (PowerShell)
.\\scripts\\deploy.ps1 -Environment pilot -Component all
\`\`\`

---

## 2. Pre-Deployment Health & Sanity Checklist

Before initiating any deployment to staging or production, run the pre-flight verification script:

\`\`\`bash
node scripts/prepare-deployment.js --clean
\`\`\`

### Automated Verifications:
1. **Dangling Artifacts:** Cleans up temporary or backup files (\`*.bak\`, \`*.tmp\`, \`*_OLD.*\`).
2. **Secret Leak Prevention:** Scans build artifacts to ensure no private keys or tokens are exposed.
3. **Environment Parity:** Verifies that all required keys in \`.env.example\` are populated in the active environment.

---

## 3. Rollback Procedure

If an issue is detected post-deployment:

### Frontend (Firebase Hosting):
\`\`\`bash
# Roll back to the previous stable release instantly:
npx firebase-tools hosting:rollback --project ${state.deployment?.clientName || 'PROJECT_ID'}
\`\`\`

### Backend (Cloud Run):
\`\`\`bash
# Route 100% of traffic back to the previous stable revision:
gcloud run services update-traffic ${state.deployment?.backendService || 'api-service'} --to-revisions=PREVIOUS_REVISION=100
\`\`\`

---

## 4. Troubleshooting & Diagnostics

| Symptom | Probable Cause | Action |
| :--- | :--- | :--- |
| **HTTP 429 Too Many Requests** | Upstream client rate limit reached | Verify \`RATE_LIMIT_PER_SEC\` config in connector SDK. |
| **Missing Environment Variable** | \`.env\` parity discrepancy | Compare local \`.env\` against \`.env.example\`. |
| **CORS Error on Frontend** | Cloud Run domain mismatch | Update \`CLIENT_URLS\` in backend environment configuration. |
`;
  }

  static generateDataDictionary(state: FdeEngagementState): string {
    const client = state.clientName || 'Client';

    let doc = `# ${client} — Data Dictionary & Field Mapping Reference\n\n`;

    if (state.schemaMappings.length === 0) {
      doc += `*No schema mappings have been generated yet. Use Phase 1 (Schema Mapper) to map client schemas.*\n`;
      return doc;
    }

    for (const m of state.schemaMappings) {
      doc += `## Staging Model: \`${m.targetModelName}\` (Source: \`${m.sourceName}\`)\n\n`;
      doc += `| Target Column | Source Column | Target Type | Transformation Rule | Confidence |\n`;
      doc += `| :--- | :--- | :--- | :--- | :---: |\n`;

      for (const col of m.columns) {
        doc += `| \`${col.targetColumn}\` | \`${col.sourceColumn}\` | \`${col.targetType}\` | \`${col.transformation || 'Direct mapping'}\` | ${Math.round(col.confidence * 100)}% |\n`;
      }
      doc += `\n`;
    }

    if ((state.dataMarts || []).length > 0) {
      doc += `## Downstream Dimensional Data Marts\n\n`;
      for (const mart of (state.dataMarts || [])) {
        doc += `### Mart: \`${mart.martName}\` (Base: \`${mart.baseModel}\`)\n\n`;
        doc += `* **Joins:** ${(mart.joins || []).map(j => `\`${j.joinType} JOIN ${j.joinModel} ON ${j.onCondition}\``).join(', ') || 'None'}\n`;
        doc += `* **Dimensions:** ${mart.dimensions.map(d => `\`${d}\``).join(', ') || 'None'}\n\n`;
        doc += `| Metric Name | Formula / Expression |\n`;
        doc += `| :--- | :--- |\n`;
        for (const metric of mart.metrics) {
          doc += `| \`${metric.name}\` | \`${metric.expr}\` |\n`;
        }
        doc += `\n`;
      }
    }

    return doc;
  }

  static generateEnvironmentCatalog(state: FdeEngagementState): string {
    const client = state.clientName || 'Client';
    const envVars = (state.discoveredEnvVars && state.discoveredEnvVars.length > 0) ? state.discoveredEnvVars : [
      'GCP_PROJECT_ID',
      'FIREBASE_TOKEN',
      'DATABASE_URL',
      'API_BEARER_TOKEN',
      'PORT'
    ];

    return `# ${client} — Environment Variables & Secrets Reference

> **Maintained by:** Forward Deployed Engineering (FDE)  
> **Target Environment:** ${state.deployment?.environment || 'pilot'}  

---

## 1. Required Runtime Configuration

| Variable Name | Required | Secret? | Description / Expected Value |
| :--- | :---: | :---: | :--- |
${envVars.map(v => {
  const isSecret = /KEY|SECRET|TOKEN|PASSWORD|AUTH|CREDENTIAL/i.test(v);
  return `| \`${v}\` | **Yes** | ${isSecret ? '🔒 Secret' : 'Public'} | Runtime configuration for \`${v}\` |`;
}).join('\n')}

---

## 2. Setup Guide

### Local Development (\`.env\`):
\`\`\`bash
cp .env.example .env
# Fill in local secrets safely
\`\`\`

### CI/CD Deployment:
Configure all secrets under GitHub Actions / GitLab CI pipeline settings before triggering automated pilot builds.
`;
  }

  static generateCompleteHandoffPackage(state: FdeEngagementState): string {
    const arch = this.generateArchitectureDoc(state);
    const deploy = this.generateDeploymentRunbook(state);
    const dataDict = this.generateDataDictionary(state);
    const env = this.generateEnvironmentCatalog(state);

    return `# 📦 ${state.clientName || 'Client'} — Complete Engagement Handoff Bundle
> **Generated on:** ${new Date().toISOString().split('T')[0]}  
> **Prepared by:** Forward Deployed Engineering Studio (Evolve AI)  

---

${arch}

---

${deploy}

---

${dataDict}

---

${env}
`;
  }
}

