/**
 * fde/runbookGenerator.ts — Client Handoff Runbook & Architecture Generator
 *
 * For Forward Deployed Engineers (FDEs) to generate complete, client-ready handoff
 * documentation at the conclusion of a pilot or engagement.
 *
 * Outputs:
 *  - ARCHITECTURE.md (with interactive Mermaid diagrams)
 *  - DEPLOYMENT_RUNBOOK.md (Client IT operations guide)
 *  - DATA_DICTIONARY.md (Column-by-column transformation mapping)
 *  - ENVIRONMENT_CATALOG.md (Environment variable reference)
 */

import { FdeEngagementState } from './fdeContext';

export class RunbookGenerator {
  static generateArchitectureDoc(state: FdeEngagementState): string {
    const client = state.clientName || 'Client';
    const targetVpc = state.targetVpc || 'gcp-firebase';

    return `# ${client} — System Architecture & Integration Blueprint

> **Generated by Evolve AI (Forward Deployed Engineer Suite)**  
> **Engagement Target:** ${client} Production & Pilot Deployment  
> **Infrastructure Target:** ${targetVpc.toUpperCase()}  

---

## 1. Executive System Overview

This document specifies the end-to-end architecture, data flows, and deployment topology implemented for the **${client}** pilot engagement.

\`\`\`mermaid
graph TD
    subgraph Client Infrastructure
        RawData["Raw Client Data\\n(CSV / Oracle / SQL)"]
        ClientApi["Client Internal APIs\\n(REST / Webhooks)"]
    end

    subgraph Data Transformation Layer
        StagingModel["dbt / Spark Staging Models\\n(Type Casts & Renaming)"]
        ResilientSdk["Resilient Connector SDK\\n(Retries & Rate Limits)"]
    end

    subgraph Cloud Delivery Layer
        Frontend["Firebase Hosting\\n(SPA + Immutable Caching)"]
        Backend["Google Cloud Run / Containers\\n(Auto-Scaling & API)"]
        Database["PostgreSQL / Supabase / Lakehouse\\n(Relational & Analytics)"]
    end

    RawData --> StagingModel
    ClientApi --> ResilientSdk
    StagingModel --> Database
    ResilientSdk --> Backend
    Frontend --> Backend
    Backend --> Database
\`\`\`

---

## 2. Ingested Data Models & Transformations

| Source Dataset | Target Model | Dialect | Status |
| :--- | :--- | :--- | :--- |
${state.schemaMappings.map(m => `| \`${m.sourceName}\` | \`${m.targetModelName}\` | \`${m.dialect}\` | Active (${m.columns.length} columns) |`).join('\n') || '| *(No schema models mapped yet)* | - | - | - |'}

---

## 3. Connected APIs & External Feeds

| Connector Name | Base URL | Auth Type | Endpoints |
| :--- | :--- | :--- | :--- |
${state.apiConnectors.map(c => `| \`${c.connectorName}\` | \`${c.baseUrl}\` | \`${c.authType}\` | ${c.endpoints.length} endpoints |`).join('\n') || '| *(No API connectors registered)* | - | - | - |'}

---

## 4. Security & Compliance Posture

* **Data Isolation:** All staging transformations and client data mappings are executed strictly within the client's VPC boundary.
* **Secret Isolation:** Environment secrets and API tokens are managed via secure runtime environment injection—never committed to source control.
* **Air-Gapped Ready:** The deployment is compatible with strict air-gapped and non-exfiltrating developer environments.
`;
  }

  static generateDeploymentRunbook(state: FdeEngagementState): string {
    const client = state.clientName || 'Client';

    return `# ${client} — Operations & Deployment Runbook

> **Audience:** Client IT, DevOps, and Platform Engineering Teams  
> **Maintained by:** Forward Deployed Engineering (FDE)  

---

## 1. Quick-Start Deployment

To deploy updates to the client environment, execute the cross-platform deployment script from the project root:

\`\`\`bash
# Linux / macOS (Bash)
./scripts/deploy.sh pilot all

# Windows (PowerShell)
.\\scripts\\deploy.ps1 -Environment pilot -Component all
\`\`\`

---

## 2. Pre-Deployment Health & Sanity Checklist

Before initiating any deployment to staging or production, run the pre-flight verification script:

\`\`\`bash
node scripts/prepare-deployment.js --clean
\`\`\`

### Automated Verifications:
1. **Dangling Artifacts:** Cleans up temporary or backup files (\`*.bak\`, \`*.tmp\`, \`*_OLD.*\`).
2. **Secret Leak Prevention:** Scans build artifacts to ensure no private keys or tokens are exposed.
3. **Environment Parity:** Verifies that all required keys in \`.env.example\` are populated in the active environment.

---

## 3. Rollback Procedure

If an issue is detected post-deployment:

### Frontend (Firebase Hosting):
\`\`\`bash
# Roll back to the previous stable release instantly:
npx firebase-tools hosting:rollback --project ${state.deployment?.clientName || 'PROJECT_ID'}
\`\`\`

### Backend (Cloud Run):
\`\`\`bash
# Route 100% of traffic back to the previous stable revision:
gcloud run services update-traffic ${state.deployment?.backendService || 'api-service'} --to-revisions=PREVIOUS_REVISION=100
\`\`\`

---

## 4. Troubleshooting & Diagnostics

| Symptom | Probable Cause | Action |
| :--- | :--- | :--- |
| **HTTP 429 Too Many Requests** | Upstream client rate limit reached | Verify \`RATE_LIMIT_PER_SEC\` config in connector SDK. |
| **Missing Environment Variable** | \`.env\` parity discrepancy | Compare local \`.env\` against \`.env.example\`. |
| **CORS Error on Frontend** | Cloud Run domain mismatch | Update \`CLIENT_URLS\` in backend environment configuration. |
`;
  }

  static generateDataDictionary(state: FdeEngagementState): string {
    const client = state.clientName || 'Client';

    let doc = `# ${client} — Data Dictionary & Field Mapping Reference\n\n`;

    if (state.schemaMappings.length === 0) {
      doc += `*No schema mappings have been generated yet. Use \`Evolve AI: Map Client Schema to Model\` to begin.*\n`;
      return doc;
    }

    for (const m of state.schemaMappings) {
      doc += `## Target Model: \`${m.targetModelName}\` (Source: \`${m.sourceName}\`)\n\n`;
      doc += `| Target Column | Source Column | Target Type | Transformation Rule | Confidence |\n`;
      doc += `| :--- | :--- | :--- | :--- | :---: |\n`;

      for (const col of m.columns) {
        doc += `| \`${col.targetColumn}\` | \`${col.sourceColumn}\` | \`${col.targetType}\` | \`${col.transformation || 'Direct mapping'}\` | ${Math.round(col.confidence * 100)}% |\n`;
      }
      doc += `\n`;
    }

    return doc;
  }
}
