/**
 * enterprise/loadTesting/loadTestGenerator.ts
 *
 * Automated Multi-Protocol Load & Stress Test Generator (k6 & Locust).
 * Evolve Mind Solutions Pty Ltd. All rights reserved.
 */

import * as path from 'path';
import { LoadTestOptions, GeneratedLoadTestSuite, LoadTestStage } from './loadTestTypes';

export class LoadTestGenerator {
  /**
   * Generates a complete load test suite containing k6, Locust, and cross-platform runners.
   */
  public static generateSuite(options: LoadTestOptions): GeneratedLoadTestSuite {
    const k6 = this.generateK6Script(options);
    const locust = this.generateLocustScript(options);
    const shell = this.generateShellRunner(options);
    const ps = this.generatePowerShellRunner(options);

    const safeName = (options.serviceName || 'pilot_api').toLowerCase().replace(/[^a-z0-9_]/g, '_');

    return {
      k6Script: k6,
      k6FilePath: path.join('tests', 'load', `k6_${safeName}.js`),
      locustScript: locust,
      locustFilePath: path.join('tests', 'load', 'locustfile.py'),
      shellRunner: shell,
      psRunner: ps,
    };
  }

  /**
   * Generates high-concurrency JavaScript k6 load testing script with SLA thresholds.
   */
  public static generateK6Script(options: LoadTestOptions): string {
    const serviceName = options.serviceName || 'ClientService';
    const targetUrl = options.targetUrl || 'http://localhost:8080/api/v1/resource';
    const method = options.method || 'GET';
    const p95 = options.sla?.p95LatencyMs || 150;
    const p99 = options.sla?.p99LatencyMs || 300;
    const errorRate = (options.sla?.maxErrorRatePercent || 1.0) / 100;

    const stages: LoadTestStage[] = options.stages || this._getDefaultStages(options.rampPreset);
    const stagesJson = JSON.stringify(stages, null, 2);

    let authSnippet = '';
    if (options.authType === 'bearer') {
      authSnippet = `    'Authorization': \`Bearer \${__ENV.API_TOKEN || 'demo-token'}\`,`;
    } else if (options.authType === 'apikey') {
      const headerName = options.authHeaderName || 'X-API-Key';
      authSnippet = `    '${headerName}': \`\${__ENV.API_KEY || 'demo-key'}\`,`;
    }

    let payloadSnippet = 'null';
    if (options.requestBody && method !== 'GET') {
      const bodyStr = typeof options.requestBody === 'string'
        ? options.requestBody
        : JSON.stringify(options.requestBody, null, 2);
      payloadSnippet = `JSON.stringify(${bodyStr})`;
    }

    return `/**
 * tests/load/k6_${serviceName.toLowerCase()}.js
 *
 * Automated k6 SLA Performance & Load Test Suite
 * Generated by Evolve AI Enterprise Edition — Evolve Mind Solutions Pty Ltd
 */

import http from 'k6/http';
import { check, sleep, group } from 'k6';
import { Rate, Trend } from 'k6/metrics';

// Custom enterprise metrics
const errorRate = new Rate('sla_error_rate');
const latencyTrend = new Trend('sla_latency_ms');

export const options = {
  // Load generation profile
  stages: ${stagesJson},

  // Strict Enterprise SLA Assertions (Pass/Fail Gates)
  thresholds: {
    // SLA Rule: 95% of requests must complete under ${p95}ms, 99% under ${p99}ms
    'http_req_duration': ['p(95)<${p95}', 'p(99)<${p99}'],
    // SLA Rule: Error rate must be under ${(errorRate * 100).toFixed(1)}%
    'http_req_failed': ['rate<${errorRate}'],
    'sla_error_rate': ['rate<${errorRate}'],
  },
};

const BASE_URL = __ENV.TARGET_URL || '${targetUrl}';

export default function () {
  group('${serviceName} Pilot SLA Test', function () {
    const headers = {
      'Content-Type': 'application/json',
      'Accept': 'application/json',
      'User-Agent': 'EvolveAI-LoadTest-VU/2.19.0',
${authSnippet}
    };

    const payload = ${payloadSnippet};
    const params = { headers: headers, timeout: '10s' };

    const startTime = Date.now();
    let res;
    if ('${method}' === 'POST') {
      res = http.post(BASE_URL, payload, params);
    } else if ('${method}' === 'PUT') {
      res = http.put(BASE_URL, payload, params);
    } else if ('${method}' === 'DELETE') {
      res = http.del(BASE_URL, payload, params);
    } else {
      res = http.get(BASE_URL, params);
    }
    const duration = Date.now() - startTime;

    latencyTrend.add(duration);

    const isSuccess = check(res, {
      'status is 2xx': (r) => r.status >= 200 && r.status < 300,
      'latency under SLA p99 (${p99}ms)': (r) => r.timings.duration < ${p99},
    });

    errorRate.add(!isSuccess);

    // Realistic user think time between 100ms and 500ms
    sleep(Math.random() * 0.4 + 0.1);
  });
}
`;
  }

  /**
   * Generates Python Locust load testing script.
   */
  public static generateLocustScript(options: LoadTestOptions): string {
    const serviceName = options.serviceName || 'ClientService';
    const targetUrl = options.targetUrl || '/api/v1/resource';
    const method = (options.method || 'GET').toLowerCase();
    const p95 = options.sla?.p95LatencyMs || 150;

    return `"""
tests/load/locustfile.py

Automated Locust Load & Stress Test
Generated by Evolve AI Enterprise Edition — Evolve Mind Solutions Pty Ltd
"""

import os
import json
from locust import HttpUser, task, between, events

class ${serviceName}LoadTestUser(HttpUser):
    # Simulated think time: 0.1 to 0.5 seconds between tasks
    wait_time = between(0.1, 0.5)

    def on_start(self):
        """Executed before each Virtual User starts running tasks."""
        self.headers = {
            "Content-Type": "application/json",
            "Accept": "application/json",
            "User-Agent": "EvolveAI-Locust-VU/2.19.0",
        }
        token = os.getenv("API_TOKEN")
        if token:
            self.headers["Authorization"] = f"Bearer {token}"

    @task(3)
    def test_primary_endpoint(self):
        """Primary traffic test task."""
        with self.client.${method}(
            "${targetUrl}",
            headers=self.headers,
            catch_response=True,
            name="${serviceName} Primary Flow"
        ) as response:
            if response.status_code >= 400:
                response.failure(f"HTTP {response.status_code}: {response.text}")
            elif response.elapsed.total_seconds() * 1000 > ${p95}:
                response.failure(f"SLA Violation: Latency > ${p95}ms ({response.elapsed.total_seconds()*1000:.1f}ms)")
            else:
                response.success()

# CLI Command:
# locust -f tests/load/locustfile.py --host=https://api.client.internal --users 500 --spawn-rate 50 --run-time 3m --headless
`;
  }

  public static generateShellRunner(options: LoadTestOptions): string {
    const safeName = (options.serviceName || 'pilot_api').toLowerCase().replace(/[^a-z0-9_]/g, '_');
    return `#!/usr/bin/env bash
# tests/load/run_load_test.sh
# Automated Load Test Runner — Evolve AI Enterprise Edition
set -e

echo "========================================================="
echo "  Evolve AI: Running k6 SLA Benchmark on ${options.serviceName}"
echo "========================================================="

if command -v k6 &> /dev/null; then
  k6 run tests/load/k6_${safeName}.js
elif command -v docker &> /dev/null; then
  echo "k6 not found locally. Running via Docker..."
  docker run --rm -i -v "\$(pwd):/app" -w /app grafana/k6 run tests/load/k6_${safeName}.js
else
  echo "[ERROR] Neither k6 CLI nor Docker was found. Please install k6 (brew install k6 / winget install k6)."
  exit 1
fi
`;
  }

  public static generatePowerShellRunner(options: LoadTestOptions): string {
    const safeName = (options.serviceName || 'pilot_api').toLowerCase().replace(/[^a-z0-9_]/g, '_');
    return `# tests/load/run_load_test.ps1
# Automated Load Test Runner — Evolve AI Enterprise Edition
Write-Host "=========================================================" -ForegroundColor Cyan
Write-Host "  Evolve AI: Running k6 SLA Benchmark on ${options.serviceName}" -ForegroundColor Cyan
Write-Host "=========================================================" -ForegroundColor Cyan

if (Get-Command k6 -ErrorAction SilentlyContinue) {
  k6 run "tests/load/k6_${safeName}.js"
} elseif (Get-Command docker -ErrorAction SilentlyContinue) {
  Write-Host "k6 not found locally. Running via Docker..." -ForegroundColor Yellow
  docker run --rm -i -v "\${PWD}:/app" -w /app grafana/k6 run "tests/load/k6_${safeName}.js"
} else {
  Write-Host "[ERROR] Neither k6 CLI nor Docker was found. Run: winget install k6" -ForegroundColor Red
}
`;
  }

  private static _getDefaultStages(preset?: 'smoke' | 'standard' | 'stress' | 'spike'): LoadTestStage[] {
    if (preset === 'smoke') {
      return [
        { duration: '30s', target: 10 },
        { duration: '1m', target: 10 },
        { duration: '15s', target: 0 },
      ];
    } else if (preset === 'stress') {
      return [
        { duration: '1m', target: 100 },
        { duration: '2m', target: 500 },
        { duration: '3m', target: 2500 },
        { duration: '1m', target: 0 },
      ];
    } else if (preset === 'spike') {
      return [
        { duration: '10s', target: 50 },
        { duration: '1m', target: 5000 },
        { duration: '10s', target: 0 },
      ];
    }
    // Standard default
    return [
      { duration: '30s', target: 50 },
      { duration: '2m', target: 250 },
      { duration: '30s', target: 0 },
    ];
  }
}
